### ISSUE TITLE
Ensure selected values remain visible

### ISSUE THREAD

**Issue by unclescooby** [typesense/showcase-songs-search#1]
## Description

Under certain circumstances selected values become invisible, so user cannot deselect them.

## Steps to reproduce

1. search for "e". Facets appear.
2. select Artist -> Various Artists
3. select Release date -> 2020s  (it just became visible)
4. deselect Artist -> Various Artists
5. Release date -> 2020s is still selected but disappears, so we cannot deselect it if we want to

## Expected Behavior

Maybe instantsearch can be configured/forced to keep showing selected values (preferably not in "show more" expansion area)

**Comment by jasonbosco** [comment]
Good catch! The `menu` widget does have [a way](https://www.algolia.com/doc/api-reference/widgets/menu/js/#widget-param-sortby) to show the currently selected item on top, but the UX felt a little confusing because once you click an item on the menu it will jump up to the top of the list from under the area where you click. 

So instead, I've now added the `currentRefinements` widgets, to show the currently selected item. This is how it now looks with the steps you listed:

<img width="1227" alt="Screen Shot 2020-11-04 at 2 47 46 PM" src="https://user-images.githubusercontent.com/458383/98176123-cef06000-1eac-11eb-9838-eb093d770f7f.png">

(Notice how it shows "2020" on the top left).
